### ISSUE TITLE
Test specific versions of aca-py agent

### ISSUE THREAD

**Issue by ianco** [openwallet-foundation/owl-agent-test-harness#109]
Would be a "nice to have" to test multiple aca-py versions, for example when we release a new aca-py version we could run a backward compatibility test against a previous version.

**Comment by swcurran** [comment]
That was the intention of the "acapy-master" type idea.  That there be an "acapy" version that ALWAYS pulled from PyPi to do the build, and there would be an "acapy-version:0.5.5" that had a different dockerfile that would pull from the aries-cloudagent-python repo with either the latest or by the tag specified following the ":".

It's tricky since the build and run steps are different, so the "acapy-version:0.5.5" would be specified at build time, and then the run would using "acapy-version" would just use whatever image was last created.  Then you could run a version against "acapy" -- the current release.

Someone started to add that feature, but it didn't get finished and I haven't got back to it.  It needs just some fun bash scripting to make that work.

**Comment by TimoGlastra** [comment]
I would suggest to not make the run and build steps different. Not specifying the version at runtime would mean you can't test ACA-Py 0.5.5 for interoperability with ACA-Py 0.5.4, which would be a great addition I think.

So it would work something like:

```sh
./manage build -a acapy@0.5.5 -a acapy@0.5.4 -a acapy -a acapy@master

./manage start -d acapy@0.5.5 -a acapy@0.5.4 -b acapy -f acapy@master
```

If no version is specified during build time the last PyPi image will be taken. If a version is used the tag / branch will be used from github. 

---

Implementation wise we could do this by building the same docker image with different tags and check which are available when running.

**Comment by swcurran** [comment]
This is a dup of #51.
