### ISSUE TITLE
How to test with postgres as database for aca-py agent.

### ISSUE THREAD

**Issue by proteche** [openwallet-foundation/owl-agent-test-harness#131]
where to pass more arguments to run postgres as database like `--wallet-storage-type postgres_storage`

**Comment by ianco** [comment]
The scripts are not currently setup to pass any extra parameters to the agents/backchannels.  All the agents are different and will have different parameters.  If you want to test aca-py with postgres you'll need to update the code - you can see how the parameters would be added here:  https://github.com/hyperledger/aries-agent-test-harness/blob/master/aries-backchannels/acapy/acapy_backchannel.py#L154 ...  you just need to set this flag on startup.

**Comment by swcurran** [comment]
This is covered by the ACA-Py BDD testing and is not really needed here.

The ACA-Py team could decide to add support for this type of thing by updating (or adding a new) dockerfile so that within the ACA-Py Test agent container, postegres is run.  Somewhat against the spirit of containers (one service per container), but completely aligned with the idea that an AATH Test Agent is a single container with both the "thing to be tested" and the backchannel.  In this case, the "thing to be tested" would be the both ACA-Py and an instance of Postgres, so both would go in the container with the backchannel.

Closing.
