### ISSUE TITLE
Javascript backchannel is not able to issue large credentials

### ISSUE THREAD

**Issue by berendsliedrecht** [openwallet-foundation/owl-agent-test-harness#166]
When I tried to issue a credential of about 100kB or more, I would get timed out after 2 minutes. 

After running some tests, Aries framework JavaScript is capable to issue credentials with a size of 5mB.

**Comment by nodlesh** [comment]
@blu3beri Are you saying that the javascript backchannel is the issue here, and that you were able to issue large credentials without the backchannel? Thanks.

**Comment by TimoGlastra** [comment]
I asked @blu3beri to open this issue because apparently the AFJ backchannel can't handle large credentials.

We've been doing some testing with embedding binary files in credentials and are happily surprised with the results (as [HIPE 0139](https://github.com/hyperledger/indy-hipe/blob/master/text/0139-image-as-cred-attr/README.md) suggested the limit was 300kb). 

We're now wondering if this should be part of the interoperability testing. For example ACA-Py can't handle files larger than 3.5mb (so base64 encoded that'd be around 5mB), while .NET is doing fine with files of 5mB.

It should be fairly easy to add a test that issues a very large credential to see if it blows up and catch potential changes in the frameworks in the future

**Comment by berendsliedrecht** [comment]
> @blu3beri Are you saying that the javascript backchannel is the issue here, and that you were able to issue large credentials without the backchannel? Thanks.

Yes, my apologies. Somehow the JavaScript backchannel limits the maximum credential size.

**Comment by nodlesh** [comment]
Ok, sounds good. Thanks for the clarifications from you both.

**Comment by ianco** [comment]
Have you identified where is the bottleneck?

FYI under the covers, the indy sdk creates an encrypted tag in the wallet for each attribute in the credential, this value is then added to an index.  We found there was a limitation with the postgres wallet on this index size, so we converted to use an MD5 hash as the index, rather than the attribute value itself.

**Comment by TimoGlastra** [comment]
I looks like that for both ACA-Py and AFJ it is a limit of the HTTP server, so it should be modifiable. We'll dive deeper to see what the exact problem is
