### ISSUE TITLE
Test harness should not require ledger and tails server to be running

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#198]
The test harness currently cannot run without the ledger and tails server also running. As those are not necessarily required for issuing linked data credentials (ATM) I think they should be optional.

Three possible options:
- Do not check (bad)
- Automatically detect with tags (hard, not possible I think)
- Add startup parameter to `./manage` to skip the checks -> I like this one

**Comment by swcurran** [comment]
What about the option of us using the public test ledgers and tails server, so that they are just running?  We can BCovrin Test and BC Gov Test Tails Server.  This adds some remote dependencies (bad) but reduce the time and cycles to run locally or with GitHub actions.   Another benefit is that it reduces "getting started" time.

If we choose this, I would recommend that we default it to remote and allow "--local" and "--noledg" overrides.
