### ISSUE TITLE
Adding new endpoint is cumbersome process

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#199]
I wanted to add a new endpoint to the test harness and found the process a bit cumbersome and not very contributor friendly.

1. Add call in test harness
2. Add handling in ACA-Py backchannel
3. Get an error because the operation is not defined in `backchannel_operations.csv`.
4. Go to the source file it is generated from in the repo: `Mapping Aries Protocols for Testing - Aries Agent Test Scripts`.
5. Notice this file is outdated, darn!
6. Go to the source google sheet file as it is a generated field.
5. This is not a publicly editable document. Clone it to my local google drive
6. Edit the file, download it to the repo as a CSV.
7. Generate the `backchannel_operations.csv` from the input document.
8. Victory
9. Next editor doesn't have the changes I made in my copy of the public google sheet.

This is an exaggerated rant, but just wanted to point out we could maybe improve the process a bit. I think keeping the `Mapping Aries Protocols for Testing - Aries Agent Test Scripts` file up to date in the repo is one way to do this. This at least allows everyone to collaborate on the input. 

But ideally I think we shouldn't depend on an external google sheets doc. With some effort we can update the generate script to utilize the open api instead of the google doc. This way the input open api can be used for all of the following:
- Add swagger UI to get a nice overview of the endpoints, expected input, expected output etc..
	- We could add a publicly hosted version on github pages, for developers to use for development (e.g. like we did with the ACA-Py interface: https://ula-aca.github.io/aries-cloudagent-interface-javascript/#/)
- Be able to import in Postman and related tools to quickly have all endpoints ready to execute. This makes backchannel development a lot easier as you can focus on building the backchannel first. Without directly running the whole test suite
- Generate the backchannel_operations file for ACA-Py (and others) to dynamically parse the operations.
- Provide example input and output (the postman collection contains results with actual request and response information from different calls)

**Comment by TimoGlastra** [comment]
I see the `genBCData` script doesn't work without modifications. It contains an incorrect path. Is this not the way to go anymore?

The `TEST_DEV_GUIDE` says you need to run this script, but the file is `.py` now. So it seems outdated?

```
./genBCdata Mapping\ Aries\ Protocols\ for\ Testing\ -\ Aries\ Agent\ Test\ Scripts.csv
```

**Comment by TimoGlastra** [comment]
Welp, seems like the public google sheet also isn't up to date. Manually combining the generated files now...

**Comment by swcurran** [comment]
@ianco -- let's get together on how to fix this.  I think the solution is to eliminate the google spreadsheet and rely on the Swagger definition, but not certain.  We certainly have to make it easier and less manual.

What would it take to eliminate the spreadsheet?  If we did that, what does it take so that we can manage the Swagger file?

**Comment by ianco** [comment]
@swcurran sure let's chat.  There are a few quick fixes though that we should do:

- Fix permissions on the existing google doc and sync up with any changes.  I notice Sheldon is actively maintaining this file (last edit 14 days ago) so with Timo cloning and changing the file we have likely diverged already.  We can either make this file global read/write or add a note to the docs saying "ask for permission if you can't edit this file".
- Fix docs regarding any existing scripts (e.g. "genBCdata.py" has always been "genBCdata.py" so the docs are just wrong)
- Maybe we can make the docs a bit more clear - sounds like Timo just jumped in without necessarily ready the "how to" docs, but if one of the csv files is out of date in github then different developers have not been following the same procedures, so at the very least we need to get everyone on the same page and make sure that 
- I like the idea of a swagger file (obviously) but the csv file is used by the backchannel itself to make sure it has received a valid request - we need a way to specify the api's in a way that the backchannel can understand.  The swagger file can be used by the backchannel *client* (the test harness, postman or whatever) but we need a configuration that can be parsed by the backchannel itself.  I'm not sure using open api would make this process easier or more developer friendly.

The existing process with the google doc and csv file was implemented for the original aath poc and hasn't really changed since, so lots of room for improvement obviously, but let's make sure we're not throwing the baby out with the bathwater ... so to speak ...

**Comment by ianco** [comment]
I put in a PR with a couple of tweaks to the dev docs (fixes script name etc) and I opened the permissions on the google sheet.  It's out of sync now with what's in the repo and I haven't (yet) tried to rationalize which is correct.

@TimoGlastra how is the openapi doc currently being generated?

**Comment by swcurran** [comment]
Would it be worth pulling the data from the live Google doc vs. having to put it into the repo?

**Comment by ianco** [comment]
It may be worth ditching the google doc and just editing the csv file in the repo directly.  Or possibly using a different format such as yml or json ...

As Timo suggests we can use the openapi file directly, but I prefer  something simpler (there will be a lot of duplication and extraneous information in the openapi file) and then generate the openapi file (in addition to the csv or whatever we import into the backchannel for validation).

Let's discuss next week.

**Comment by TimoGlastra** [comment]
> * Fix permissions on the existing google doc and sync up with any changes.  I notice Sheldon is actively maintaining this file (last edit 14 days ago) so with Timo cloning and changing the file we have likely diverged already.  We can either make this file global read/write or add a note to the docs saying "ask for permission if you can't edit this file".

I cloned the file just before generating the data. I think it was already outdated. Please see #206. This automatically downloads the sheet as csv + xlsx. So we're always up to date, and the repo always contains the source files for the currently generated file. In the case we have diverged, we can always compare.

> Maybe we can make the docs a bit more clear - sounds like Timo just jumped in without necessarily ready the "how to" docs, but if one of the csv files is out of date in github then different developers have not been following the same procedures, so at the very least we need to get everyone on the same page and make sure that

That's not fair. The google sheet gave me different results than were currently generated in the repo, meaning I had to manually combine the generated fields. No amount of reading could have fixed that.

> * I like the idea of a swagger file (obviously) but the csv file is used by the backchannel itself to make sure it has received a valid request - we need a way to specify the api's in a way that the backchannel can understand.  The swagger file can be used by the backchannel _client_ (the test harness, postman or whatever) but we need a configuration that can be parsed by the backchannel itself.  I'm not sure using open api would make this process easier or more developer friendly.

Why does the backchannel need to parse the backchannel operations? To guard the test harness from making incorrect requests? Seems like a lot of work to validate an API call in a test suite. I've added two backchannels to this repo, and haven't found the need for it TBH.

Seems to me like we need a clear overview for backchannel developers to know which API endpoints they should implement, and what the expected request / response types are. I think a hosted API spec is perfectly suited for this task (https://aries-interop.info/api). I'm not sure why we need to reinvent the wheel for specifying how an API should look / behave.

If you want to do validation on the backchannel side, we can reuse existing tools (e.g. [openapi-core](https://pypi.org/project/openapi-core/) for python) to validate incoming requests.

> As Timo suggests we can use the openapi file directly, but I prefer something simpler (there will be a lot of duplication and extraneous information in the openapi file) and then generate the openapi file (in addition to the csv or whatever we import into the backchannel for validation).

I agree using an OpenAPI file adds some overhead, but I think it can add a lot of useful information about expected input / output, meaning of the different http status codes, descriptions and information about requests, actual backchannel request / response samples. If we can get all that in a source format to generate the OpenAPI file from I'm in (it seems like we're recreating the open api format then). But I'm interested to explore this further, maybe I want too much from the OpenAPI file.

> @TimoGlastra how is the openapi doc currently being generated?

It isn't! As pointed out in my note above this one, I'm interested to explore the possibilities. 

---

That said, I think keeping the Google sheet and generated files up to date already helps a lot. Thanks for the updates and comments Ian!

**Comment by swcurran** [comment]
Closing for now and we'll evolve as new ideas come up.
