### ISSUE TITLE
Run test harness on PR

### ISSUE THREAD

**Issue by TimoGlastra** [openwallet-foundation/owl-agent-test-harness#257]
Currently the CI runs on a daily schedule. I think it will be beneficial to run the CI as part of a PR. So we choose two, e.g. ACA-PY <--> AFGO, AFJ <--> AFD just to make sure we haven't broken anything as part of the PR.

As the CI is already in place this would be an easy addition

**Comment by TimoGlastra** [comment]
Reopening as the CI on pr has been disabled. This will make reviewing PRs a lot easier and remove the manual step of needing to run it locally

**Comment by nodlesh** [comment]
@TimoGlastra @ryjones 
This was added and disabled once before. There are 2 maybe 3 issues that need to be addressed before running this on a PR.

1. The action to run on a PR should not contain the generate summary results job. Otherwise the results of the PR will merge with the official results in https://aries-interop.info
2. The run test actions need to not call the run-send-gen-test-results-secure. This will update our official results in our Allure Reporting Service. Of course, if you don't have the secrets setup for Allure then this will fail, but then the problem below in 3 will happen.  This means that PR executions will need to run a different set of test-harness-* workflows.
3. When these fail I think the repo admins get email notifications. Not sure if they want PR failures flooding their inbox. @swcurran

**Comment by nodlesh** [comment]
Would need Reports turned off. 
So new workflows, new conditions in the existing workflows.

**Comment by ryjones** [comment]
@nodlesh PR for review: https://github.com/hyperledger/aries-agent-test-harness/pull/489
