### ISSUE TITLE
Mobile Tests in AATH need rework due to auto respond support

### ISSUE THREAD

**Issue by nodlesh** [openwallet-foundation/owl-agent-test-harness#330]
The more we try to accommodate other agents, the more divergent the mobile test execution becomes. It is different than a regular agent. 

Some of the mobile tests are working, different results with Trinsic Wallet or esatus. This work item requires one to dive into what is making the tests fail with the mobile wallets and either fix it or decide to separate mobile tests from other tests. 

One approach may be to make a `mobile.feature` file and add all the mobile tests there. Remove the `MobileTest` tag in the other features file. This gives us a clear variable to check in code to bypass anything that isn't going to work for mobile. ie ` context.feature.featurename == mobile`

**Comment by swcurran** [comment]
I think we try to fix the mobile tests — they should work given the premise of the test suite.  We want the same tests running as much as possible.  So I think that should be the first goal — and we determine it’s really not possible.

I’m not a big fan of the alternative way to use other than tags for selection.  Could we accomplish the same thing by having a MobileOnly flag and use that to exclude such tests?

I’m still a bit confused as to why from a test harness perspective, the auto respond feature matters.  I can see that the backchannels have to handle it, but the test harness shouldn’t care, since there is nothing in the RFC that talks about auto-respond.  I can see using a Test Agent (e.g. acapy-main)  specific flag to test a particular Test Agent on its auto or non-auto handling, but I don’t see how the test harness should need to know that.  That doesn’t feel right to me.

**Comment by nodlesh** [comment]
Yes agreed, we need to determine what is wrong. Maybe I am overstating the case to separate. 

The only reason I mentioned checking the feature name is because it would be the only way to bypass or include code paths that is strictly supporting Mobile. If a new test case, let's say in Issue Credential feature file, has the MobileOnly tag, then yes that would serve the same purpose. 

Auto Respond doesn't matter to the Test Harness. The Test Harness side doesn't know.  It does matter to the backchannel. The backchannel is the only thing that knows we are in auto respond mode. The backchannel doesn't know we are running mobile tests, so something is happening in that flow with the removal of interim state checks that is causing the some mobile tests to fail.

**Comment by nodlesh** [comment]
This ticket was created since I'm hoping we can merge the auto respond PR without this mobile issue fixed so other backchannel developers can take advantage of the auto respond support enhancement. Then we can go back to this and figure out the mobile problem.
